# Generated by Django 4.0.3 on 2022-04-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('main_image', models.TextField(null=True)),
                ('variantsString', models.TextField(null=True)),
                ('drawFunction', models.TextField(null=True)),
                ('publish_datetime', models.DateTimeField()),
            ],
        ),
    ]
