# Generated by Django 4.0.3 on 2022-04-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='main_image',
            new_name='mainImage',
        ),
    ]
